application:
  title: User Management
  version: v.0.0.1

spring:
  webflux:
    base-path: "/api"
  datasource:
    host: localhost
    port: 5432
    database: users
    username: SecretUser
    password: SecretPass
  flyway:
    url: localhost
    user: SecretUser
    password: SecretPass
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 9999
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always

logging:
  level:
    root: info

